### ISSUE TITLE
Versioning system that is easily supported by the verifier and by DOI versioning

### ISSUE THREAD

**Issue by dcferreira** [CN-TU/nta-meta-analysis-specification#14]
We need to find a versioning system that is flexible enough to be able to add/change content between releases (e.g., add content to ``own_ies.csv``), while still being static enough so that the DOIs generated by Zenodo refer to something meaningful.

This issue is to collect requirements for such a versioning system.

Things to remember:
- We use ``v2.1`` to refer to the latest revision made to the format; the documentation should be static with respect to this version
- When curating papers for the already existing ``v2.1``, we often need to change/add new things (fix bugs in schema/code, add IEs that are not from IANA)
- Sometimes it is also necessary to fix bugs in old versions, meaning we can't completely keep old vesions static

We need:
1. Releases that refer to the static documentation version, which should be the same as is in the actual JSON files (this right now is ``v2`` or ``v2.1``); these may not change in the future, as they will have a DOI attached
2. External tools must be able to resolve ``v2.1`` to the latest corresponding commit
3. Even though documentation should be static, we should also be able to change it (to improve descriptions, add pages for tools, whatever else), without actually changing the specification. It's OK if the DOI points to a version of the documentation with less content, as long as the actual specification is constant

**Comment by notti** [comment]
Well I think a single version of a schema should be static, too. Otherwise, if we fix something in the schema it would result in weird things during validation ("Hey this file validates here with v2.1 - why is this invalid at your place?")
So I would vote for [semantic versioning](https://semver.org/), which means:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

So basically everything starting with `2.1.x` can be parsed with `2.1.x` tools, `2.y.x` can only be parsed with `2.z.x` tools where `z` >= `y` and, `1` is completely incompatible with `2`.

This should allow keeping documentation and code in the same repository, since the always have the latest version, which is also able to parse the earlier versions.
Only hard thing to decide is whether something is PATCH or a MINOR change, since adding new IEs could already be a MINOR, since older version don't recognise this IE.

**Comment by dcferreira** [comment]
It seems easy to distinguish MINOR from PATCH; MINOR is anything that changes the actual specification (meaning, what the documentation says is valid/invalid), PATCH is everything else.
However, I'm not sure that solves problem 2. above.

Another suggestions:
Have one branch for each MAJOR.MINOR version, and make exactly one release in each of these branches, and keep it static. Then, smaller changes (PATCH) are just inserted into the branch after the release, and external tools look at the latest commit in the branch instead of the release.
The problem with this approach is that releases and branches share the namespace, meaning the branch needs to have a different name than the version.

**Comment by notti** [comment]
> External tools must be able to resolve v2.1 to the latest corresponding commit

What's the reason behind this?
> It seems easy to distinguish MINOR from PATCH; MINOR is anything that changes the actual specification (meaning, what the documentation says is valid/invalid), PATCH is everything else.

Well which is actually everything, including adding stuff to own_ies.csv, since the documentation says, that features starting with _ must be in own_ies.csv.

> Have one branch for each MAJOR.MINOR version, and make exactly one release in each of these branches, and keep it static. Then, smaller changes (PATCH) are just inserted into the branch after the release, and external tools look at the latest commit in the branch instead of the release.

Well that is really cumbersome for tools, since it is not easy to get that information. Also it seems fishy to me, that the file says "I'm version v2.1", but it actually means "Oh I'm not really v2.1 - I'm at some commit level in v2.1 - guess which one". So it's actually impossible to verify what has gone wrong after some time.

**Comment by dcferreira** [comment]
> > External tools must be able to resolve v2.1 to the latest corresponding commit

> What's the reason behind this?

For example the verifier used in Travis need to be aware of the latest IEs added to ``own_ies.csv``, so that new valid files are considered valid.

> > It seems easy to distinguish MINOR from PATCH; MINOR is anything that changes the actual specification (meaning, what the documentation says is valid/invalid), PATCH is everything else.

> Well which is actually everything, including adding stuff to own_ies.csv, since the documentation says, that features starting with _ must be in own_ies.csv.

Exactly. So that problem seems like a non-issue to me.

>> Have one branch for each MAJOR.MINOR version, and make exactly one release in each of these branches, and keep it static. Then, smaller changes (PATCH) are just inserted into the branch after the release, and external tools look at the latest commit in the branch instead of the release. 

> Well that is really cumbersome for tools, since it is not easy to get that information.

What do you mean? Pulling the branch should get you the latest version.

> Also it seems fishy to me, that the file says "I'm version v2.1", but it actually means "Oh I'm not really v2.1 - I'm at some commit level in v2.1 - guess which one". So it's actually impossible to verify what has gone wrong after some time.

This is true. What are the alternatives here though? Add a PATCH tag to each commit in one of the release branches? This seems cumbersome.

**Comment by notti** [comment]
> For example the verifier used in Travis need to be aware of the latest IEs added to own_ies.csv, so that new valid files are considered valid.

No, actually it doesn't, since the version in the file already tells you, with which version it needs to be compatible.
So steps would be:
1. read version field from json file
2. switch to branch named like this version (if this branch does not exist -> already an error)
3. call the verifier

Also another simpler (although not strictly correct) way would be:
Checkout the latest branch (since as mentioned above MINOR and PATCH both need to be backwards compatible) and just use the latest branch for verifying.

> > >  It seems easy to distinguish MINOR from PATCH; MINOR is anything that changes the actual specification (meaning, what the documentation says is valid/invalid), PATCH is everything else.

> >  Well which is actually everything, including adding stuff to own_ies.csv, since the documentation says, that features starting with _ must be in own_ies.csv.

> Exactly. So that problem seems like a non-issue to me.

Well in this case we could leave out the PATCH level, if this is the same.

> > >  Have one branch for each MAJOR.MINOR version, and make exactly one release in each of these branches, and keep it static. Then, smaller changes (PATCH) are just inserted into the branch after the release, and external tools look at the latest commit in the branch instead of the release.

> > Well that is really cumbersome for tools, since it is not easy to get that information.

> What do you mean? Pulling the branch should get you the latest version.

I don't know where the branch came from (I have not proposed making branches).
Well there are already tools out there that don't pull (editor).


So to finally clarify:

I would use only tags. e.g. right now it is v2.1
But this tag always stays at the same target. Now an own_ie gets added, and you want to make a new release (or some time passes by and you make a new release) this was is now called v2.2. But it is only allowed to make backwards compatible changes (e.g. including a new IE - but this would not allow removing an IE).

With this scheme a v2.2 verifier can verify both v2.2 and v2.1. But a v2.1 verifier might not verify a v2.2 file. This is ok since the file has the version in it.
With this scheme, the latest tagged verifier can still verify every v2.1 and later paper.

A new branch would only be needed if we introduce a change that is not backwards compatible. This would then need a major version increase (v3).

**Comment by dcferreira** [comment]
So this seems to be the final decision:
- One branch for each minor version, named ``rMAJOR.MINOR`` (e.g., ``r2.1``).
- Starting from v2.1.1, we use semantic versioning
- Each change that doesn't break backwards compatibility increments the PATCH number of the version (e.g., adding possible values to fields with finite possible values; adding new IEs to ``own_ies.csv``)
- This version is included in the NTARC ``version`` field
- External tools usually only need to care about MINOR version, as everything should be backwards compatible (in particular, this should be true for the verifier)
- Tags with PATCH should be very frequent; they should be used for individual commits, or for multiple commits in a short time (minutes)
- Versions v2.0 and v2.1 are exempt from this for now, but any further alterations in the r2 and r2.1 branches should be tagged with the new versions
- The r2 branch (corresponding to v2.0.X) is exempt from the proposed branch naming scheme, to keep compatibility with existing tools

**Comment by dcferreira** [comment]
This has been done and added to the documentation.
